### ISSUE TITLE
Can't compile to JS. Get an empty html file

### ISSUE THREAD

**Issue by edoloughlin** [mauricemach/coffeekup#13]
If I create a file, templates.coffee, that contains this gist: https://gist.github.com/743651 and I compile it using 
    coffeekup templates.coffee 

then I get a file, templates.html that contains a single space chacter. My understanding is that I could compile to JS and get a templates.js file out. Is this incorrect?

**Comment by mauricemach** [comment]
Currently the coffeekup command only handles compilation to html... there isn't a wrapper for coffeekup.compile yet.

Anyway, in your gist you're assigning your templates to variables. That's why you get an empty output. To get html output (or js when we have the wrapper) the file should contain a template body.

**Comment by mauricemach** [comment]
You can now compile to JS with `coffeekup --js` in 0.3.0.
