### ISSUE TITLE
dynamic_locals not documented

### ISSUE THREAD

**Issue by jaekwon** [mauricemach/coffeekup#15]
I think I had to use dynamic_locals to get locals to work correctly with recursion. Does this ring a bell?

Anyways, I found a nifty option parameter that did the trick, so I figured this would be nice in the docs. 

I'm compiling coffee on the server side (@1.0.0) and running CK on the client.

**Comment by mauricemach** [comment]
Sorry for that! Now 0.3.0beta uses `with` by default (since it's the behaviour expected by most people), and the equivalent to `dynamic_locals` is passing an object named `hardcode`. This is all documented in the new [reference](https://github.com/mauricemach/coffeekup/blob/master/docs/reference.md).

**Comment by jaekwon** [comment]
hazzah, +1 for `with` support.
