### ISSUE TITLE
caching.

### ISSUE THREAD

**Issue by aaronblohowiak** [mauricemach/coffeekup#19]
looks like expressjs is caching incorrectly -- it won't re-render the page with new data.

**Comment by dce** [comment]
I'm seeing the same thing. Is this an Express issue or a CK one?

**Comment by focusaurus** [comment]
I tested the combination of layout.coffee + index.coffee and layout.coffee is cached permanently and never reloaded.  (index.coffee can be edited and it will be re-rendered though). If I do layout.jade + index.jade, I can edit layout.jade and it will get re-rendered.  Thus I believe it's coffeekup's internal cache.

**Comment by mauricemach** [comment]
Express now uses `ck.compile` directly, so it handles caching on its own. I tested coffeekup and jade in development and production to confirm and both are working the same way.

Anyway, since this is the expected behaviour by most people, I also changed `ck.render` to set `cache` to `false` by default. It's pushed to master and will land on npm as 0.3.0beta.
