### ISSUE TITLE
Compile on the fly

### ISSUE THREAD

**Issue by ouvanous** [mauricemach/coffeekup#3]
Hi, 

Do you think it is possible to have coffekup compile automatically like coffee -cw ? 
I also would like to know if it is possible in this way to render template in a template ? 

e.g : 
html ->
  head ->
    @render 'mytemplate.coffee'

Many thanks for coffeekup 

Samuel

**Comment by ouvanous** [comment]
forget to tell that render a template in a template via coffeekup command line ?

**Comment by mauricemach** [comment]
Hi Samuel,

"compile automatically like coffee -cw" - I'm all for that. In fact the CLI tool needs some love. I'll work on it and post back here when it's ready.

nested rendering - You can certainly do this already, see this [gist](http://gist.github.com/644214). You can even define it as a local (just `render` instead of `@render`), which I think is preferrable since the context (`@`) is a good namespace for data.

Just remember that this approach is synchronous, it's opening a file and blocking until the contents can be returned, so it's not a good fit for run time. But for the CLI it would certainly make sense, since blocking at build time is usually not an issue. So I think we could have the CLI tool include a `render` local like this for us automatically, even though it's not in the library itself. Is that what you're thinking too?

**Comment by ouvanous** [comment]
Hi Maurice and thanks for your response. 
That is exactly what i need ! 
I want to use coffeekup for prototyping with less for css. 
So i can use template and component (e.g nav.coffee, layout.coffee, ...) and generate (automatically) by command line (with watch options the html files) 
The code with coffeekup is extremly clear : thanks ;-) 
Is it possible to have html generated formatted correctly ? (with indent and new lines, ...)
I think that the code generated now isonly  in one line ? 
I don't know if you know less.app ? http://incident57.com/less/ but this is how i use css now it is extremly quick to prototype with it. 
Based on you recommandations i've done this that is what i need for now 
ck = require 'coffeekup'
fs = require 'fs'
sys = require 'sys'
fs.readdir('.', (err, files)->
  files.forEach((f)->
    if (f.indexOf '.coffeekup')
      render f
      watch f
  )
)
render = (file) ->
  code = fs.readFileSync file, 'utf8'
  ck.render code, context: @

watch = (source, base) ->
  fs.watchFile source, {persistent: true, interval: 500}, (curr, prev) ->
    return if curr.size is prev.size and curr.mtime.getTime() is prev.mtime.getTime()
    fs.readFile source, (err, code) ->
      throw err if err
      sys.log ck.render(code.toString(), locals: {render: render})

Many thanks, 

Samuel

**Comment by mauricemach** [comment]
Just pushed a new version with:

`-w`: Watches and recompiles just like `coffee`

`-u`: Adds helper locals to your templates (only `render` currently)

`-f`: Formats the output HTML with line breaks. I'll add indentation too in the future. This option is also available from the API (`CoffeeKup.render tpl, format: yes`)

Please tell me if I got it right!

**Comment by mauricemach** [comment]
PS: This version is not on npm yet, to check it out you can clone the repo and run `npm link .` at the package dir.

**Comment by ouvanous** [comment]
Wow ! many thanks Maurice.
I will test that this evening but it seems very nice.
Once i 'll have little time I will try to make a little logo for coffeekup ;-)
Many thanks again !

**Comment by mauricemach** [comment]
Well that would be great!

I've been thinking of something along the lines of a coffee... cup... between brackets. But if you think it's too cheesy, I can certainly understand! =D
