### ISSUE TITLE
Allow parsing of XML files

### ISSUE THREAD

**Issue by fhemberger** [mauricemach/coffeekup#53]
It would be cool to use Coffeekup also for XML files (e.g. RSS or ATOM).
Because of the tag checking, this currently does not work:

```
doctype 'xml'
rss(version: '2.0') ->
  channel ->
    title 'Title'
    link 'URL'
    description '…'

    item ->
      title '…'
      link '…'
```

**Comment by mauricemach** [comment]
You're right, it's a stupid limitation, since the engine is already prepared to render arbitrary XML.

One quick solution would be something I was planning to do anyway - to expose the `tags` collection, in the same way I already did with `doctypes`, allowing them to be customized.

We could also have pre-made tag lists to popular formats such as RSS, in a separate module.

**Comment by fhemberger** [comment]
Why do you restrict the `tags` collection anyway? Just to ensure valid (X)HTML?

Instead you could check incoming tags against a regular expression to avoid invalid characters, something like:
`/[a-zA-Z][-_:a-zA-Z0-9]/` (first char must always be letter, if I recall correctly)

**Comment by mauricemach** [comment]
No, I'm not actually trying to ensure valid anything. We need a tag list because each tag in CoffeeKup is a function that has to be declared.

**Comment by mauricemach** [comment]
Exposed the collection in [3ca049](https://github.com/mauricemach/coffeekup/commit/3ca049a193af09dab4d30adab4b0cb06aaa06bfb).
