### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by lorensr** [mauricemach/coffeekup#54]
```
h2 ->
  h3 -> 'foo'
  'bar'
```

correctly gives:

```
<h2>
  <h3>
    foo
  </h3>
  bar
</h2>
```

but when the text is placed first:

```
h2 ->
  'bar'
  h3 -> 'foo'
```

it does not appear in the output:

```
<h2>
  <h3>
    foo
  </h3>
</h2>
```

**Comment by mauricemach** [comment]
It's a very common and understandable misconception that I'm going to clarify further in the 0.3.0 docs.

CoffeeKup is not parsed, it's not a language: it's a library that takes HTML-resembling functions (which are meant to be written in CoffeeScript, but in fact could even be JavaScript just as well!) and makes some modifications to them so that when executed, they'll return the equivalent HTML string.

One of these modifications is adding the `__ck.buffer` variable to it. This is an array of strings that will be joined and returned. The only way to have contents in the final output document is to push to this buffer. So another modification is adding the `text` function, which will write arbitrary text to the buffer.

All "tag" functions use `text` internally. That's why they can be anywhere inside a function and they'll still write to the buffer, as long as they are being executed.

But literal text alone in one line is just an empty CoffeeScript/JavaScript statement (`'foo';`). It doesn't do anything, so it can't write to the buffer. That's why the `text` function exists.

But literal text as the _last evaluated expression_ of a function (usually the last line but not always), on the other hand, would be an empty statement in _JavaScript_ too, but in _CoffeeScript_ it's an implicit return. So the parent function can take this return value and write it to the buffer. This is "syntax sugar" to allow things like `div -> @body` and `p -> 'text'`.

Maybe writing returned values to the buffer should go away, since it's causing a lot of confusion, and you can just as well do `div @body` and `p 'text'` which are more readable anyway. Or maybe it should stay but not be mentioned in examples, only in the (soon to be added) reference.
