### ISSUE TITLE
Dynamic view helpers from express

### ISSUE THREAD

**Issue by randallb** [mauricemach/coffeekup#60]
Because of the eval-ing going on, I don't think dynamic view helpers can access stuff they'd normally be able to access, preventing me from using the default CSRF express tools w/ Coffeekup.

I'm going to probably write my own middleware as a result.

**Comment by mauricemach** [comment]
You mean https://github.com/hanssonlarsson/express-csrf? I couldn't get it working with their readme example + jade (got "Unexpected identifier"). Can you point me to a working sample?

I also ran a little dynamic helpers test with CoffeeKup and they seem to be working fine. I can't think of why they shouldn't. The only "eval-ing" going on in CoffeeKup is at the time of compiling the template (use of the Function constructor), which since express started expecting a `.compile` method, I believe is the case with most templating engines.

If you could post a gist with an express app similar to yours, using a dynamic helper, working with another templating engine, but choking with CK, that would help a lot.

**Comment by randallb** [comment]
I'm going to close this for now... I expect to try dynamic view helpers in a day or two.

**Comment by mauricemach** [comment]
ok!
