### ISSUE TITLE
JS error on coffeekup.org

### ISSUE THREAD

**Issue by jbr** [mauricemach/coffeekup#7]
Uncaught Error: When creating object "editor", there is no factory called "text_editor" available."
BespinEmbedded.js:7875

UserAgent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_8; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.28 Safari/534.10

Hope that helps

**Comment by mauricemach** [comment]
That could happen sometimes because I was using my own detection instead of window.onBespinLoad, as I had some previous problems with it. Now you brought up the problem again I looked further into it and managed to incorporate it properly.

If you still have issues with the newer version, please let me know.

Thanks a lot!
