### ISSUE TITLE
why do we need both context and local vars?

### ISSUE THREAD

**Issue by flippyhead** [mauricemach/coffeekup#9]
What's the difference between the two save that context vars are referenced by @'s ?

**Comment by mauricemach** [comment]
Well since CK templates are nothing but coffeescript/javascript functions we'll always have both. The `@` is just coffeescript's shortcut syntax to `this`.

One implementation difference is that the `this`/`@` is always an actual reference to the original object you passed in as "context". On the other hand the properties of the object passed in as "locals" are made available to your templates either by hardcoding them on the compiled function's body (the default, which is faster but has limited application), or by the use of the keyword `with` (if you pass in the option `dynamic_locals: yes`).

Personally I think `this`/`@` makes for a good place for your data, since the local scope is already "polluted" with the 117 predefined HTML elements. Helper functions, specially those intended to be used in the same way as elements (like in the facebook example from the other issue) I think are better unprefixed. But it's mostly really up to your preferences.

**Comment by aldonline** [comment]
Great clarification.
Maurice may I suggest you take some time to document some of your design decisions?

Annotated source ( a la CoffeeScript ) is cheap to produce and it will save you from tons of ( important ) questions like this one in the future.

Your projects are spot on the money.

**Comment by mauricemach** [comment]
Indeed aldo! Next on my coffeekup list is documentation. Jeremy's docco is a gift and it's a shame not to use it.

**Comment by dvv** [comment]
Frankly, I'd start to get rid of `with(){}`, because of ES5 in strict mode is stated to be the future, and they deprecate `with`. It's always good to have only one source of data, and `@var` is far clearer than `with(locals){foo = 'bar'}`. OTOH, `@` may not be preserved in deeper levels (say, callbacks to `.forEach()` or `.map()`). What if consider robust and consistent technique: to assign context to Z, to extend Z with locals and to require to refer the data as Z.foo. Two additional characters are not too much, Z.foo won't ever throw "foo is not declared", no chances to pollute the global object.

--Vladimir

**Comment by mauricemach** [comment]
Since CoffeeKup is free of the `with` keyword by default (you just have the _option_ of using it by passing `dynamic_locals: yes`) I don't see a problem here. Options are (almost) always good.

**Comment by dvv** [comment]
Right. Remain does the inconsistency of `this` in deeper functions: `@arr.forEach (x) -> @arr === undefined`. You propose to use `=>` in such cases?

**Comment by mauricemach** [comment]
Yes, and that's what I prefer personally. But if you don't want to / can't use the fat arrow, you can put all your data in a local. Zappa provides the `params` local for example. You could put all your data in your `Z` local as well, it's entirely up to you.

By the way, when you pass `locals` to CoffeeKup, you're not polluting the global namespace. They're exactly what the name says: local variables. They're only visible at your template's scope.

**Comment by dvv** [comment]
I see. By polluting I meant accidental `with(...){$=1;}` which could result in window.jQuery being wiped out, or variations on the same motive at server-side. OK. Thanks for clarifying things.

--Vladimir
